create database formBD;

--2) SEXO = {CODSEXO, NOMESEXO}
CREATE TABLE SEXO(
CODSEXO INT identity(1,1) PRIMARY KEY,
NOMESEXO VARCHAR (9) NOT NULL UNIQUE
);
--3) RUA = {CODRUA, NOMERUA}
CREATE TABLE RUA (
CODRUA INT identity(1,1) PRIMARY KEY,
NOMERUA VARCHAR (80) NOT NULL UNIQUE
);
--4) BAIRRO = {CODBAIRRO, NOMEBAIRRO}
CREATE TABLE BAIRRO(
CODBAIRRO INT identity(1,1) PRIMARY KEY,
NOMEBAIRRO VARCHAR (80) NOT NULL UNIQUE
);
--5) CEP = {CODCEP, NUMEROCEP}
CREATE TABLE  CEP (
CODCEP INT identity(1,1) PRIMARY KEY,
NUMEROCEP CHAR(15) NOT NULL UNIQUE
);
--7) UF = {CODUF, NOMEUF, SIGLA}
CREATE TABLE UF(
CODUF INT identity(1,1) PRIMARY KEY,
NOMEUF VARCHAR (80) NOT NULL UNIQUE,
SIGLA CHAR (2) NOT NULL UNIQUE
);

--6) CIDADE = {CODCIDADE, NOMECIDADE, CODUF}
CREATE TABLE CIDADE (
CODCIDADE INT identity(1,1) PRIMARY KEY,
NOMECIDADE VARCHAR(80) NOT NULL UNIQUE,
CODUF_FK INT FOREIGN KEY REFERENCES UF(CODUF) 
);

--8) TRABALHO = {CODTRABALHO, NOMETRABALHO}
CREATE TABLE TRABALHO(
CODTRABALHO INT identity(1,1) PRIMARY KEY,
NOMETRABALHO VARCHAR(80) NOT NULL
);
/*1) CLIENTE = {CODCLIENTE, NOMECLIENTE, FOTO, DATANASC, CODSEXO_FK, CODRUA_FK,
CODBAIRRO_FK, CODCEP_FK, CODCIDADE_FK, SALARIO, CODTRABALHO_FK, NUMEROCASA_FK}*/
CREATE TABLE CLIENTE(
CODCLIENTE INT  identity(1,1) PRIMARY KEY,
NOMECLIENTE VARCHAR(80) NOT NULL,
FOTO VARBINARY(MAX) NOT NULL,
DATANASC VARCHAR(80) NOT NULL,
CODSEXO_FK INT FOREIGN KEY REFERENCES SEXO(CODSEXO) ,
CODRUA_FK INT FOREIGN KEY REFERENCES RUA(CODRUA) ,
CODBAIRRO_FK INT FOREIGN KEY REFERENCES BAIRRO(CODBAIRRO),
CODCEP_FK INT FOREIGN KEY REFERENCES CEP(CODCEP),
CODCIDADE_FK INT FOREIGN KEY REFERENCES CIDADE(CODCIDADE),
SALARIOCLIENTE NUMERIC (10,2) NOT NULL,
CODTRABALHO_FK INT FOREIGN KEY REFERENCES TRABALHO(CODTRABALHO),
NUMEROCASA VARCHAR (10) NOT NULL
);

--10) OPERADORA = {CODPERADORA, NOMEOPERADORA}
CREATE TABLE OPERADORA (
CODOPERADORA INT PRIMARY KEY,
NOMEOPERADORA VARCHAR(80) NOT NULL UNIQUE
); 
--9) TELEFONE = {CODTELEFONE, NUMERO, CODOPERADORA}
CREATE TABLE TELEFONE (
CODTELEFONE INT  identity(1,1) PRIMARY KEY,
NUMERO CHAR (9) NOT NULL UNIQUE,
CODOPERADORA_FK INT FOREIGN KEY REFERENCES OPERADORA(CODOPERADORA)
);

--11) ITENSTELCLIENTE = {CODTELEFONE, CODCLIENTE}
CREATE TABLE ITENSTELCLIENTE (
CODTELEFONE_FK INT FOREIGN KEY REFERENCES TELEFONE(CODTELEFONE),
CODCLIENTE_FK INT FOREIGN KEY REFERENCES CLIENTE(CODCLIENTE)
);
--12) ITENSTELEFONETRABALHO = {CODTRABALHO, CODTELEFONE}
CREATE TABLE ITENSTELEFONETRABALHO(
CODTRABALHO_FK INT FOREIGN KEY REFERENCES TRABALHO(CODTRABALHO),
CODTELEFONE_FK INT FOREIGN KEY REFERENCES TELEFONE(CODTELEFONE) 
);
--15) FUNCAO = {CODFUNCAO, NOMEFUNCAO}
CREATE TABLE FUNCAO(
CODFUNCAO INT identity(1,1) PRIMARY KEY,
NOMEFUNCAO VARCHAR (80) NOT NULL UNIQUE
);

--21) LOJA = {CODLOJA, NOMELOJA, CNPJ, NOMEFANTASIA, RAZAOSOCIAL}
CREATE TABLE LOJA(
CODLOJA INT identity(1,1) PRIMARY KEY,
NOMELOJA VARCHAR (80) NOT NULL,
CNPJ CHAR (20) NOT NULL UNIQUE,
NOMEFANTASIA VARCHAR(80) NOT NULL,
RAZAOSOCIAL VARCHAR(80) NOT NULL UNIQUE
);
/*13) FUNCIONARIOS = {CODFUNCIONARIO, NOMEFUNCIONARIO, NUMEROCASA,
CODRUA, CODBAIRRO, CODCEP, CODCIDADE, CODFUNCAO, SALARIO, CODLOJA}*/
CREATE TABLE FUNCIONARIOS(
CODFUNCIONARIOS INT identity(1,1) PRIMARY KEY,
NOMEFUNCIONARIO VARCHAR(80) NOT NULL,
NUMEROCASA VARCHAR(10) NOT NULL,
CODRUA_FK INT FOREIGN KEY REFERENCES RUA(CODRUA),
CODBAIRRO_FK INT FOREIGN KEY REFERENCES BAIRRO(CODBAIRRO),
CODCEP_FK INT FOREIGN KEY REFERENCES CEP(CODCEP),
CODCIDADE_FK INT FOREIGN KEY REFERENCES CIDADE(CODCIDADE),
CODFUNCAO_FK INT FOREIGN KEY REFERENCES FUNCAO(CODFUNCAO),
SALARIOFUNCIONARIO NUMERIC (10,2) NOT NULL,
CODLOJA_FK INT FOREIGN KEY REFERENCES LOJA(CODLOJA) 
);

--16) ITENSTELEFONEFUNCIONARIO = {CODFUNCIONARIO, CODTELEFONE}
CREATE TABLE ITENSTELEFONEFUNCIONARIO(
CODFUNCIONARIO_FK INT FOREIGN KEY REFERENCES FUNCIONARIOS(CODFUNCIONARIOS),
CODTELEFONE_FK INT FOREIGN KEY REFERENCES TELEFONE(CODTELEFONE) 
);
--17) LOGIN = {CODLOGIN, USUARIO, SENHA, CODFUNCIONARIO}
CREATE TABLE LOGIN(
CODLOGIN INT identity(1,1) PRIMARY KEY,
USUARIO VARCHAR(80) NOT NULL UNIQUE,
SENHA CHAR(40) NOT NULL,
CODFUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(CODFUNCIONARIOS)
);
--18) CONTROLELOGSISTEMA = {CODCONTROLE, CODLOGIN, DATA, HORA}
CREATE TABLE CONTROLELOGSISTEMA(
CODCONTROLE INT PRIMARY KEY,
CODLOGIN_FK INT FOREIGN KEY REFERENCES LOGIN(CODLOGIN),
DATAS DATE NOT NULL
);
--19) ACESSO = {CODACESSO, NOMEACESSO}
CREATE TABLE ACESSO(
CODACESSO INT identity(1,1) PRIMARY KEY,
NOMEACESSO VARCHAR(80) NOT NULL UNIQUE
);
--20) ITENSACESSOLOGIN = {CODACESSO, CODLOGIN}
CREATE TABLE ITENSACESSOLOGIN(
CODACESSO_FK INTEGER REFERENCES ACESSO(CODACESSO),
CODLOGIN_FK INT FOREIGN KEY REFERENCES LOGIN(CODLOGIN) 
);

--22) ITENSTELEFONELOJA={CODLOJA, CODTELEFONE}
CREATE TABLE ITENSTELEFONELOJA(
CODLOJA_FK INT FOREIGN KEY REFERENCES LOJA(CODLOJA),
CODTELEFONE_FK INT FOREIGN KEY REFERENCES TELEFONE(CODTELEFONE)
);
--24) MARCA={CODMARCA, NOMEMARCA}
CREATE TABLE MARCA(
CODMARCA INT identity(1,1) PRIMARY KEY,
NOMEMARCA VARCHAR(80) NOT NULL UNIQUE
);
--25) TIPO={CODTIPO, NOMETIPO}
CREATE TABLE TIPO(
CODTIPO  INT identity(1,1) PRIMARY KEY,
NOMETIPO VARCHAR(80) NOT NULL UNIQUE
);

/*23) PRODUTO = {CODPRODUTO, NOMEPRODUTO, QUANTIDADE, VALOR, CODMARCA,
CODTIPO }*/
CREATE TABLE PRODUTO(
CODPRODUTO INT identity(1,1) PRIMARY KEY,
NOMEPRODUTO VARCHAR(80) UNIQUE,
QUANTIDADE NUMERIC(10,2) NOT NULL,
VALOR NUMERIC(10,2) NOT NULL,
CODMARCA_FK INT FOREIGN KEY REFERENCES MARCA(CODMARCA),
CODTIPO_FK INT FOREIGN KEY REFERENCES TIPO(CODTIPO) 
);

/*26) FORNECEDOR={CODFORNECEDOR, NOMEFORNECEDOR, NUMEROCASA, CORUA,
CODBAIRRO, CODCEP, CODCIDADE}*/
CREATE TABLE FORNECEDOR(
CODFORNECEDOR INT identity(1,1) PRIMARY KEY,
NOMEFORNECEDOR VARCHAR(80) NOT NULL UNIQUE,
NUMEROCASA VARCHAR(10) NOT NULL,
CODCIDADE_FK INT FOREIGN KEY REFERENCES CIDADE(CODCIDADE),
CODRUA_FK INT FOREIGN KEY REFERENCES RUA(CODRUA),
CODBAIRRO_FK INT FOREIGN KEY REFERENCES BAIRRO(CODBAIRRO),
CODCEP_FK INT FOREIGN KEY REFERENCES CEP(CODCEP) 
);
--27) ITENSTELEFONEFORNECEDOR={CODTELEFONE, CODFORNECEDOR}
CREATE TABLE ITENSTELEFONEFORNECEDOR(
CODTELEFONE_FK INT FOREIGN KEY REFERENCES TELEFONE(CODTELEFONE),
CODFORNECEDOR_FK INT FOREIGN KEY REFERENCES FORNECEDOR(CODFORNECEDOR) 
);
/*28) COMPRAPRODUTO = {CODCOMPRA, DATACOMPRA, CODFORNECEDOR,
CODFUNCIONARIO}*/
CREATE TABLE COMPRAPRODUTO(
CODCOMPRA INT PRIMARY KEY,
DATACOMPRA DATE NOT NULL,
CODTELEFONE_FK INT FOREIGN KEY REFERENCES TELEFONE(CODTELEFONE) ,
CODFORNECEDOR_FK INT FOREIGN KEY REFERENCES FORNECEDOR(CODFORNECEDOR),
CODFUNCIONARIO_FK INT FOREIGN KEY REFERENCES FUNCIONARIOS(CODFUNCIONARIOS)
);
--29) ITENSCOMPRAPRODUTO = {CODCOMPRA, CODPRODUTO, QUANTIDADE, VALORC}
CREATE TABLE ITENSCOMPRAPRODUTO(
CODCOMPRA_FK INT FOREIGN KEY REFERENCES COMPRAPRODUTO(CODCOMPRA),
CODPRODUTO_FK INT FOREIGN KEY REFERENCES PRODUTO(CODPRODUTO),
QUANTIDADES NUMERIC (10,2) NOT NULL,
VALORC NUMERIC(10,2) NOT NULL
);
--31) SITUACAO = {CODSITUACAO, NOMESITUACAO}
CREATE TABLE SITUACAO(
CODSITUACAO INT identity(1,1) PRIMARY KEY,
NOMESITUACAO VARCHAR(80) NOT NULL UNIQUE
);
/*30) PARCELACOMPRA = {CODPARCELACOMPRA, DATAVENCIMENTO, VALOR,
CODSITUACAO, CODCOMPRA}*/
CREATE TABLE PARCELACOMPRA(
CODPARCELACOMPRA INT identity(1,1) PRIMARY KEY,
DATAVENCIMENTO DATE NOT NULL,
VALORP NUMERIC (10,2) NOT NULL,
CODSITUACAO_FK INT FOREIGN KEY REFERENCES SITUACAO(CODSITUACAO),
CODCOMPRA_FK INT FOREIGN KEY REFERENCES COMPRAPRODUTO(CODCOMPRA)
);

--32) VENDAPRODUTO = {CODVENDA, DATAVENDA, CODCLIENTE, CODFUNCIONARIO}
CREATE TABLE VENDAPRODUTO(
CODVENDA INT identity(1,1) PRIMARY KEY,
DATAVENDA DATE NOT NULL,
CODCLIENTE_FK INT FOREIGN KEY REFERENCES CLIENTE(CODCLIENTE),
CODFUNCIONARIO_FK INT FOREIGN KEY REFERENCES FUNCIONARIOS(CODFUNCIONARIOS) 

);
--33) ITENSVENDAPRODUTO = {CODVENDA,CODPRODUTO, QUANTIDADE, VALOR}
CREATE TABLE ITENSVENDAPRODUTO(
CODVENDA_FK INT FOREIGN KEY REFERENCES VENDAPRODUTO(CODVENDA),
QUANTIDADEITENVENDA NUMERIC (10,2) NOT NULL,
VALORITENSVENDA NUMERIC (10,2) NOT NULL
);
/*34) PARCELAVENDA={CODPARCELA, DATAVENCIMENTO, VALOR, CODSITUACAO,
CODVENDA}*/
CREATE TABLE PARCELAVENDA(
CODPARCELA INT identity(1,1) PRIMARY KEY,
DATAVENCIMENTO DATE NOT NULL,
VALORPARCELA NUMERIC (10,2) NOT NULL,
CODFUNCIONARIO_FK INT FOREIGN KEY REFERENCES FUNCIONARIOS(CODFUNCIONARIOS),
CODSITUACAO_FK INT FOREIGN KEY REFERENCES SITUACAO(CODSITUACAO),
CODVENDA_FK INT FOREIGN KEY REFERENCES VENDAPRODUTO(CODVENDA)
);
--35) IMAGENS={CODIMAGENS, IMAGEM, DESCRICAO, CODPRODUTO}
CREATE TABLE IMAGENS(
CODIMAGENS INT identity(1,1) PRIMARY KEY,
IMAGEN VARBINARY(MAX) NOT NULL,
DESCRICAO VARCHAR(120) NOT NULL,
CODPRODUTO_FK INT FOREIGN KEY REFERENCES PRODUTO(CODPRODUTO)
);
select * from sexo;